[project]
name = "wikipedia-in-space"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "huggingface-hub>=1.4.1",
    "python-dotenv>=1.2.1",
    "sentence-transformers>=5.2.2",
    "thefuzz>=0.22.1",
    "wikipedia>=1.4.0",
]
